# Generated by Django 5.2.6 on 2025-09-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_relative_path', models.CharField(max_length=1024, unique=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
