# Generated by Django 5.2.6 on 2025-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
    ]
